apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-rc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-demo-rc
          image: seanshih/node-js-demo
          ports:
            - containerPort: 8080